apiVersion: v1
kind: Service
metadata:
  name: {{ include "orders.fullname" . }}-{{ .Values.database.rabbitmq.name }}
  labels:
    {{- toYaml .Values.database.labels_rabbitmq | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.database.rabbitmq.ports.amqp.port }}
      targetPort: {{ .Values.database.rabbitmq.ports.amqp.targetPort }}
      protocol: TCP
      name: amqp
    - port: {{ .Values.database.rabbitmq.ports.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- toYaml .Values.database.selector_rabbitmq | nindent 4 }}