apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "carts.fullname" . }}-{{ .Values.dynamodb.name }}
  labels:
    {{- toYaml .Values.labels_dynamodb | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    {{- toYaml .Values.strategy | nindent 8 }}
  selector:
    matchLabels:
      {{- toYaml .Values.selector_dynamodb | nindent 6 }}
  template:
    metadata:
      labels:
              {{- toYaml .Values.selector_dynamodb | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.dynamodb.name }}
          image: "{{ .Values.dynamodb.image}}:{{ .Values.dynamodb.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.dynamodb.name }}
              containerPort: {{ .Values.dynamodb.port }}
              protocol: TCP
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
