apiVersion: v1
kind: Service
metadata:
  name: {{ include "carts.fullname" . }}-{{ .Values.dynamodb.name }}
  labels:
    {{- toYaml .Values.labels_dynamodb | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.dynamodb.port }}
      targetPort: {{ .Values.dynamodb.name }}
      protocol: TCP
      name: {{ .Values.dynamodb.name }}
  selector:
    {{- toYaml .Values.selector_dynamodb | nindent 4 }}
