Applications in production:
   Frontend:
     - deployment
     - service
     - service account
     - secret (optional)
     - configmap (optional)
     - poddisruptionbuget
     - horizontalpodautoscaler
     - networkpolicy 
   api: 
     - deployment
     - service
     - service account
     - secret 
     - configmap 
     - poddisruptionbuget
     - horizontalpodautoscaler
     - networkpolicy 

   backend: 
     - statefulset
     - service
     - service account
     - secret 
     - configmap 
     - poddisruptionbuget
     - horizontalpodautoscaler
     - networkpolicy 
     - persistancevolume (optional)
     - persistancevolumeClaim (optional)
     - job (optional)
     - cronjob (optional)


