apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-thomisis
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob-thomisis
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Abeg pay attention
          restartPolicy: OnFailure
