apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  initContainers:
  - name: init-first
    image: busybox:1.28
    command: ['sh', '-c', "sleep 34 ;  until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 60; done"]
  - name: init-second
    image: busybox:1.28
    command: ['sh', '-c', "sleep 34 ; until nslookup mydb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 70; done"]
  - name: init-third
    image: busybox:1.28
    command: ['sh', '-c', "sleep 34 ;  until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 60; done"]
  - name: init-fourth
    image: busybox:1.28
    command: ['sh', '-c', "sleep 64 ; until nslookup mydb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 70; done"]
