apiVersion: v1
kind: Service
metadata:
  name: {{ include "orders.fullname" . }}-{{ .Values.database.mysql.name }}
  labels:
    {{- toYaml .Values.database.labels_mysql | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.database.mysql.port }}
      targetPort: {{ .Values.database.mysql.name }}
      protocol: TCP
      name: {{ .Values.database.mysql.name }}
  selector:
    {{- toYaml .Values.database.selector_mysql | nindent 4 }}