apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbvolume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /var/lib/postgresql/data1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbvolume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  volumeName: dbvolume

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
    apps_name: thunderstorm
spec:
  selector:
    matchLabels:
      app: db
      apps_name: thunderstorm
  replicas: 1
  template:
    metadata:
      labels:
        app: db
        apps_name: thunderstorm
    spec:
      containers:
        - name: dbvolume
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: john
            - name: POSTGRES_PASSWORD
              value: example
            - name: POSTGRES_DB
              value: endgame
            - name: DB_HOST
              value: db
          volumeMounts:
            - name: dbvolume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: dbvolume
          persistentVolumeClaim:
            claimName: dbvolume

