apiVersion: v1
kind: Service
metadata:
  labels:
    apps: adminer
  name: adminer
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 8080
  selector:
    apps: adminer
  type: NodePort

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: adminer
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: adminer
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: adminer
    spec:
      containers:
        - image: adminer
          name: adminer
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always

