apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: dbvolume
  name: dbvolume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  serviceName: db
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: endgame
            - name: POSTGRES_PASSWORD
              value: example
            - name: POSTGRES_USER
              value: john
          image: postgres
          name: db
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data-data
              name: dbvolume
  volumeClaimTemplates:
    - metadata:
        name: dbvolume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
