apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    apps: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: frontend
  template:
    metadata:
      labels:
        apps: frontend
    spec:
      containers:
        - image: kemvoueric/endgamefrontend
          name: frontend
          ports:
            - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  labels:
    apps: frontend
  name: frontend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    apps: frontend
  type: NodePort
