version: '3.5'

services:
  db:
    container_name: thomisis-db
    image: devopseasylearning/thomisis-db:v0.0.1
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - thomisis
    restart: always

  redis:
    container_name: thomisis-redis
    image: redis
    networks:
      - thomisis
    environment:
      REDIS_USER: redis
      REDIS_PASSWORD: redis
    volumes:
      - redis-data:/data
    restart: always

  weather:
    container_name: thomisis-weather
    image: devopseasylearning/thomisis-weather:v0.0.1
    expose:
      - 5000
    environment:
      APIKEY: ecbc396f46mshb65cbb1f82cf334p1fcc87jsna5e962a3c542
    networks:
      - thomisis
    restart: always
    depends_on:
      - db
      - redis  # Weather depends on both db and redis
  auth:
    container_name: thomisis-auth
    image: devopseasylearning/thomisis-auth:v0.0.1
    environment:
      DB_HOST: db
      DB_PASSWORD: my-secret-pw
    expose:
      - 8080
    networks:
      - thomisis
    restart: always
    depends_on:
      - weather  # Auth depends on the weather service

  ui:
    container_name: thomisis-ui
    image: devopseasylearning/thomisis-ui:v0.0.1
    environment:
     eric: eric
     AUTH_HOST: auth
     AUTH_PORT: 8080
     WEATHER_HOST: weather
     WEATHER_PORT: 5000
     REDIS_USER: redis
     REDIS_PASSWORD: redis
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - thomisis
    restart: always
    depends_on:
      - auth  # UI depends on Auth
networks:
  thomisis:

volumes:
  db-data:
  redis-data:
