{{- if .Values.second_set.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "catalog.fullname" . }}
data:
  DB_ENDPOINT: {{ include "catalog.fullname" . }}-{{ .Values.database.name }}:{{ .Values.database.data.port }}
  DB_READ_ENDPOINT: {{ include "catalog.fullname" . }}-{{ .Values.database.name }}:{{ .Values.database.data.port }}
  DB_NAME: {{ include "catalog.fullname" . }}
{{- end }}