{{- if .Values.second_set.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "catalog.fullname" . }}-db
data:
  username: {{ .Values.database.data.username | quote }}
  password: {{ .Values.database.data.password_2 | quote  }}
{{- end }}