{{- if .Values.second_set.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "catalog.fullname" . }}-{{ .Values.database.name }}
  labels:
    {{- toYaml .Values.database.labels | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.database.data.port }}
      targetPort: {{ .Values.database.name }}
      protocol: TCP
      name: {{ .Values.database.name }}
  selector:
    {{- toYaml .Values.database.selector | nindent 4 }}
{{- end }}