NAME: shop-product
LAST DEPLOYED: Mon Jan  8 21:38:11 2024
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
MANIFEST:
---
# Source: shop-product/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shop-product
  labels:
    helm.sh/chart: shop-product-0.1.0 
    version: v1
    app.kubernetes.io/name: shop-product
    app.kubernetes.io/instance: shop-product
    app: shop-product
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: shop-product/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: shop-product
  labels:
    helm.sh/chart: shop-product-0.1.0 
    version: v1
    app.kubernetes.io/name: shop-product
    app.kubernetes.io/instance: shop-product
    app: shop-product
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 8091
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: shop-product
    app.kubernetes.io/instance: shop-product
    app: shop-product
---
# Source: shop-product/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-product
  labels:
    helm.sh/chart: shop-product-0.1.0 
    version: v1
    app.kubernetes.io/name: shop-product
    app.kubernetes.io/instance: shop-product
    app: shop-product
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: shop-product
      app.kubernetes.io/instance: shop-product
      app: shop-product
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shop-product
        app.kubernetes.io/instance: shop-product
        app: shop-product
    spec:
      serviceAccountName: shop-product
      securityContext:
        {}
      containers:
        - name: shop-product
          securityContext:
            {}
          image: "devopseasylearning/s6-project-expressso-product:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
# Source: shop-product/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shop-product
  labels:
    helm.sh/chart: shop-product-0.1.0 
    version: v1
    app.kubernetes.io/name: shop-product
    app.kubernetes.io/instance: shop-product
    app: shop-product
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shop-product
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80

NOTES:
1. Get the application URL by running these commands:
  export NODE_PORT=$(kubectl get --namespace default -o jsonpath="{.spec.ports[0].nodePort}" services shop-product)
  export NODE_IP=$(kubectl get nodes --namespace default -o jsonpath="{.items[0].status.addresses[0].address}")
  echo http://$NODE_IP:$NODE_PORT
